language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
# develop seems to be required by travis since 02/2013
  - python setup.py build develop
  - sudo gpg --keyserver hkp://subkeys.pgp.net --recv-keys 16126D3A3E5C1192
  - sudo gpg --export --armor 16126D3A3E5C1192 | sudo apt-key add -
  - sudo apt-get clean
  - sudo apt-get install -qq zsh
  - sudo pip install vcstools nose-cov coverage pyyaml coveralls
# Set git config to silence some stuff in the tests
  - git config --global user.email "foo@example.com"
  - git config --global user.name "Foo Bar"
# Set the hg user
  - echo -e "[ui]\nusername = Your Name <your@mail.com>" >> ~/.hgrc
# Set the bzr user
  - bzr whoami "Your Name <name@example.com>"
# command to run tests
script:
  - python -c 'import sys; print(sys.path)'
  - nosetests --with-coverage --cover-package=wstool
notifications:
  email: false
after_success:
  - coveralls